### ISSUE TITLE
Move Sales wiki to gitbook

### ISSUE THREAD

**Issue by amitaibu** [Gizra/Gizra-Way-Book#2]
We should move all the content from the [old](https://github.com/Gizra/sales/wiki) sales wiki to the book (we'll delete the old wiki once it's done)

**Comment by amitaibu** [comment]
@RachelBaram ^^

**Comment by RachelBaram** [comment]
I moved all the content. You can delete the old sales wiki. @amitaibu

**Comment by amitaibu** [comment]
👍
