### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra-Way-Book#4]
We need to determine taxonomy.  Example: "Preparation for new employee" should not be under "training". @amitaibu

**Comment by amitaibu** [comment]
It's not - it should be under `HR`, which is now missing. Probably git issues -- I'll check

**Comment by amitaibu** [comment]
Weird, I remember moving it to HR. Anyway, should be fixed now

![introduction_ _the_gizra_way](https://cloud.githubusercontent.com/assets/125707/15584192/256cd66e-2382-11e6-9e09-a12337f1029c.jpg)
