### ISSUE TITLE
Sales - determine performance indicators

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra-Way-Book#5]
@amitaibu I found a great source that does research on sales effectiveness and provides resources. I created a [chapter](https://www.gitbook.com/book/amitaibu/the-gizra-way/edit#/edit/master/measuring_performance.md) about measuring performance. I included the list from this resource as a starting point to determine what works for Gizra.

**Comment by amitaibu** [comment]
Thanks. I think it's not the right direction, as the book should hold the "tried and working" methods.

Lets have an offline call about it :)
