### ISSUE TITLE
Edit Gitbook forbidden

### ISSUE THREAD

**Issue by liatsade** [Gizra/Gizra-Way-Book#51]
@amitaibu is something changed in my permissions?

I tried to access to the editing area in GitBook and got this:

![forbidden_ _gitbook](https://cloud.githubusercontent.com/assets/20393485/19853377/8e9fdd78-9f71-11e6-8519-6a6203348000.jpg)

Also in GitHub I got this, even though I'm not in the Master branch:

![editing_gizra-way-book_message_stack_md_at_message-stack_ _gizra_gizra-way-book](https://cloud.githubusercontent.com/assets/20393485/19853636/2510a7aa-9f73-11e6-8ea9-3f2406764655.jpg)

**Comment by amitaibu** [comment]
Should be fixed now.

**Comment by liatsade** [comment]
Works now, thanks.
