### ISSUE TITLE
Skill development - training development

### ISSUE THREAD

**Issue by RachelBaram** [Gizra/Gizra-Way-Book#8]
@amitaibu Here is a list of skills that are important for sales and account managers. I need your input to whether there is a Gizra Way best practice for each of these. This will help determine training that needs to be developed.
- Negotiation
- Communication
- Presentation
- Meeting management
- Project management (also applicable to team leads)
- Networking skills
- Selling
- Growth Planning (account manager specific)
- Services knowledge
- Market knowledge
- Company knowledge

**Comment by amitaibu** [comment]
Closing this in favor of smaller issues
