### ISSUE TITLE
Site Down Actions Scenarios [2h]

### ISSUE THREAD

**Issue by noamoss** [Gizra/Gizra-Way-Book#93]
https://docs.google.com/spreadsheets/d/1kPEXR7zYNi-cyPhVPGSfaTlncVYzLfCufipNIs5j-Mg/edit?usp=sharing

**Comment by AronNovak** [comment]
I did my first round of editing in the table, I'll keep the things in mind and return back a bit later with hopefully fresh ideas.

**Comment by adamhstewart** [comment]
@noamoss It would be a good idea to add a client-side Site Down procedure to our documentation as well. I just created one for a client [here](https://github.com/Gizra/jep-main/wiki/Site-Down-Procedure) 

As an aside to this, in poking around statuscake,l I noticed the ability to make public status pages... a great option in particular for our clients that have more then one site. I made one for this client as a test. An alternate for this in the procedure would be to instruct the client to check the site from a different location if possible.

Another aside - I do think we should have a "support@gizra.com" email (or something like it) that is monitored 24/7 for the last line of defense for a client.

cc/ @efratn @RachelBaram

**Comment by noamoss** [comment]
@IshaDakota 

> It would be a good idea to add a client-side Site Down procedure to our documentation as well. I just created one for a client

Right. updated the Project Status Kit doc, and linked this [template](https://docs.google.com/document/d/19T6j0a6MjUhXiKx1eNuojXLW8W_H1FCcJnz06OhCUdE/edit?usp=sharing) 


>As an aside to this, in poking around statuscake,l I noticed the ability to make public status pages... a great option in particular for our clients that have more than one site. I made one for this client as a test. An alternate for this in the procedure would be to instruct the client to check the site from a different location if possible.

great, included it in the doc, alongside the option to add client's to the StatusCake email alerts.


>An alternate for this in the procedure would be to instruct the client to check the site from a different location if possible.

Included in the client wiki entry. 

>Another aside - I do think we should have a "support@gizra.com" email (or something like it) that is monitored 24/7 for the last line of defense for a client.

What about connecting this support @gizra.com into the SiteHealth / Project slack channel?
I leave it out of the wiki template for now, until there will be such a procedure. Giving clients a support email address without anyone watching it is not a good idea, and for the meanwhile, I assume the PM is the "support" email.

**Comment by AronNovak** [comment]
@noamoss I am ready on my side, I tried to cover a larger spectrum of site downs, for instance we have a row about a security incident too.
To be included in the book, it would need a technical and non-technical proofread as well, I think.

**Comment by AronNovak** [comment]
@noamoss can we de-assign it from me or to close it, so i don't have it as assigned at https://github.com/issues/assigned ? Thank you!

**Comment by noamoss** [comment]
The [technical doc](https://docs.google.com/spreadsheets/d/1kPEXR7zYNi-cyPhVPGSfaTlncVYzLfCufipNIs5j-Mg/edit?usp=sharing) went through proofreading by Brice. @IshaDakota I am waiting for your OK on the [client wiki entry](https://docs.google.com/document/d/19T6j0a6MjUhXiKx1eNuojXLW8W_H1FCcJnz06OhCUdE/edit)
 and then we can publish on the Gizrabook.

**Comment by adamhstewart** [comment]
@noamoss looks good to me.

**Comment by noamoss** [comment]
@AronNovak Brice asked you to add something to the protocol:

>We had an issue with winners SSL today, +aron@gizra.com can you add the steps taken to analyse the problem. Thanks.


Please let me know here when done.

**Comment by AronNovak** [comment]
@noamoss done
